from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *

class Ui_formLogin(object):
    def setupUi(self, formLogin):
        if not formLogin.objectName():
            formLogin.setObjectName(u"formLogin")
        formLogin.resize(380, 235)
        formLogin.setMinimumSize(QSize(380, 235))
        formLogin.setMaximumSize(QSize(380, 235))
        formLogin.setWindowIcon(QIcon('./Gambar/logo.jpg'))
        self.labelJudul = QLabel(formLogin)
        self.labelJudul.setObjectName(u"labelJudul")
        self.labelJudul.setGeometry(QRect(125, 30, 134, 23))
        self.labelJudul.setStyleSheet('color : white')
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelJudul.setFont(font)
        self.background_logo = QLabel(formLogin)
        self.background_logo.setObjectName(u"background_logo")
        self.background_logo.setGeometry(QRect(0,0, 380, 235))
        self.background_logo.setStyleSheet('''
        background-image : url(./Gambar/logo.jpg);
        background-size : cover;
        background-position : center;
        ''')
        self.kolom_username = QLineEdit(formLogin)
        self.kolom_username.setObjectName(u"kolom_username")
        self.kolom_username.setGeometry(QRect(110, 70, 191, 31))
        self.kolom_password = QLineEdit(formLogin)
        self.kolom_password.setEchoMode(QLineEdit.Password)
        self.kolom_password.setObjectName(u"kolom_password")
        self.kolom_password.setGeometry(QRect(110, 120, 191, 31))
        self.username = QLabel(formLogin)
        self.username.setObjectName(u"username")
        self.username.setGeometry(QRect(40, 80, 58, 16))
        self.username.setStyleSheet('color : white')
        font1 = QFont()
        font1.setPointSize(10)
        self.username.setFont(font1)
        self.password = QLabel(formLogin)
        self.password.setObjectName(u"password")
        self.password.setGeometry(QRect(40, 130, 55, 16))
        self.password.setStyleSheet('color : white')
        self.password.setFont(font1)
        self.tombolLogin = QPushButton(formLogin)
        self.tombolLogin.setObjectName(u"tombolLogin")
        self.tombolLogin.setGeometry(QRect(310, 190, 51, 31))
        self.tombolLogin.setFont(font1)
        font = QFont()
        font.setPointSize(9)
        self.tombolRegister = QPushButton(formLogin)
        self.tombolRegister.setObjectName(u"tombolRegister")
        self.tombolRegister.setGeometry(QRect(250, 190, 51, 31))
        self.tombolRegister.setFont(font)
        self.background_logo.raise_()
        self.kolom_username.raise_()
        self.kolom_password.raise_()
        self.password.raise_()
        self.tombolLogin.raise_()
        self.tombolRegister.raise_()
        self.labelJudul.raise_()
        self.username.raise_()
        self.retranslateUi(formLogin)
        QMetaObject.connectSlotsByName(formLogin)

    def retranslateUi(self, formLogin):
        formLogin.setWindowTitle(QCoreApplication.translate("formLogin", u"Ten Rentals - Login", None))
        self.labelJudul.setText(QCoreApplication.translate("formLogin", u"TEN RENTALS", None))
        self.username.setText(QCoreApplication.translate("formLogin", u"Username", None))
        self.password.setText(QCoreApplication.translate("formLogin", u"Password", None))
        self.tombolLogin.setText(QCoreApplication.translate("formLogin", u"Login", None))
        self.tombolRegister.setText(QCoreApplication.translate("formLogin", u"Register", None))
