from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormRegister(object):
    def setupUi(self, FormRegister):
        FormRegister.setObjectName("FormRegister")
        FormRegister.resize(380, 300)
        FormRegister.setMinimumSize(QtCore.QSize(380, 300))
        FormRegister.setMaximumSize(QtCore.QSize(380, 300))
        FormRegister.setWindowIcon(QtGui.QIcon('./Gambar/logo.jpg'))
        FormRegister.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.register_text = QtWidgets.QLabel(FormRegister)
        self.register_text.setGeometry(QtCore.QRect(100, 20, 183, 24))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.register_text.setFont(font)
        self.register_text.setObjectName("register_text")
        self.username_text = QtWidgets.QLabel(FormRegister)
        self.username_text.setGeometry(QtCore.QRect(60, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")
        self.password_text = QtWidgets.QLabel(FormRegister)
        self.password_text.setGeometry(QtCore.QRect(60, 110, 64, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_text.setFont(font)
        self.password_text.setObjectName("password_text")
        self.email_text = QtWidgets.QLabel(FormRegister)
        self.email_text.setGeometry(QtCore.QRect(60, 150, 64, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_text.setFont(font)
        self.email_text.setObjectName("email_text")
        self.username = QtWidgets.QLineEdit(FormRegister)
        self.username.setGeometry(QtCore.QRect(140, 64, 171, 27))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(FormRegister)
        self.password.setGeometry(QtCore.QRect(140, 104, 171, 27))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.email = QtWidgets.QLineEdit(FormRegister)
        self.email.setGeometry(QtCore.QRect(140, 144, 171, 27))
        self.email.setObjectName("email")
        self.register_btn = QtWidgets.QPushButton(FormRegister)
        self.register_btn.setGeometry(QtCore.QRect(237, 200, 75, 23))
        self.register_btn.setObjectName("register_btn")
        self.back_btn = QtWidgets.QPushButton(FormRegister)
        self.back_btn.setGeometry(QtCore.QRect(160, 200, 75, 23))
        self.back_btn.setObjectName("back_btn")
        self.watermark_text = QtWidgets.QLabel(FormRegister)
        self.watermark_text.setGeometry(QtCore.QRect(160, 280, 67, 13))
        self.watermark_text.setObjectName("watermark_text")
        self.retranslateUi(FormRegister)
        QtCore.QMetaObject.connectSlotsByName(FormRegister)

    def retranslateUi(self, FormRegister):
        _translate = QtCore.QCoreApplication.translate
        FormRegister.setWindowTitle(_translate("FormRegister", "Ten Rentals - Register"))
        self.register_text.setText(_translate("FormRegister", "Form Pendaftaran"))
        self.username_text.setText(_translate("FormRegister", "Username : "))
        self.password_text.setText(_translate("FormRegister", "Password :"))
        self.email_text.setText(_translate("FormRegister", "E-Mail :"))
        self.register_btn.setText(_translate("FormRegister", "Daftar"))
        self.back_btn.setText(_translate("FormRegister", "Kembali"))
        self.watermark_text.setText(_translate("FormRegister", "@Ten Rentals"))
