from PyQt5 import QtCore, QtGui, QtWidgets
material = ['jenis_mobil', 'lama_peminjaman', 'biaya', 'username', 'nama', 'nohp', 'alamat']

class Ui_formPemesanan(object):
    def setupUi(self, formPemesanan):
        formPemesanan.setObjectName("formPemesanan")
        formPemesanan.resize(420, 500)
        formPemesanan.setMinimumSize(QtCore.QSize(420, 500))
        formPemesanan.setMaximumSize(QtCore.QSize(420, 500))
        formPemesanan.setWindowIcon(QtGui.QIcon('./Gambar/logo.jpg'))
        formPemesanan.setWindowFlag(QtCore.Qt.WindowCloseButtonHint, False)
        self.judul_text = QtWidgets.QLabel(formPemesanan)
        self.judul_text.setGeometry(QtCore.QRect(114, 20, 192, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.judul_text.setFont(font)
        self.judul_text.setObjectName("judul_text")
        self.jenis_mobil_text = QtWidgets.QLabel(formPemesanan)
        self.jenis_mobil_text.setGeometry(QtCore.QRect(40, 90, 78, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.jenis_mobil_text.setFont(font)
        self.jenis_mobil_text.setObjectName("jenis_mobil_text")
        self.nama_text = QtWidgets.QLabel(formPemesanan)
        self.nama_text.setGeometry(QtCore.QRect(40, 270, 49, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nama_text.setFont(font)
        self.nama_text.setObjectName("nama_text")
        self.lama_text = QtWidgets.QLabel(formPemesanan)
        self.lama_text.setGeometry(QtCore.QRect(40, 120, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lama_text.setFont(font)
        self.lama_text.setObjectName("lama_text")
        self.biaya_text = QtWidgets.QLabel(formPemesanan)
        self.biaya_text.setGeometry(QtCore.QRect(40, 150, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.biaya_text.setFont(font)
        self.biaya_text.setObjectName("biaya_text")
        self.rental_text = QtWidgets.QLabel(formPemesanan)
        self.rental_text.setGeometry(QtCore.QRect(40, 60, 58, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.rental_text.setFont(font)
        self.rental_text.setObjectName("rental_text")
        self.pelanggan_text = QtWidgets.QLabel(formPemesanan)
        self.pelanggan_text.setGeometry(QtCore.QRect(40, 180, 90, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pelanggan_text.setFont(font)
        self.pelanggan_text.setObjectName("pelanggan_text")
        self.nohp_text = QtWidgets.QLabel(formPemesanan)
        self.nohp_text.setGeometry(QtCore.QRect(40, 300, 56, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nohp_text.setFont(font)
        self.nohp_text.setObjectName("nohp_text")
        self.alamat_text = QtWidgets.QLabel(formPemesanan)
        self.alamat_text.setGeometry(QtCore.QRect(40, 330, 56, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.alamat_text.setFont(font)
        self.alamat_text.setObjectName("alamat_text")
        self.jenis_mobil = QtWidgets.QLineEdit(formPemesanan)
        self.jenis_mobil.setGeometry(QtCore.QRect(179, 85, 181, 25))
        self.jenis_mobil.setText("")
        self.jenis_mobil.setReadOnly(True)
        self.jenis_mobil.setObjectName("jenis_mobil")
        self.lama_peminjaman = QtWidgets.QLineEdit(formPemesanan)
        self.lama_peminjaman.setGeometry(QtCore.QRect(180, 118, 181, 25))
        self.lama_peminjaman.setReadOnly(True)
        self.lama_peminjaman.setObjectName("lama_peminjaman")
        self.biaya = QtWidgets.QLineEdit(formPemesanan)
        self.biaya.setGeometry(QtCore.QRect(180, 150, 181, 25))
        self.biaya.setReadOnly(True)
        self.biaya.setObjectName("biaya")
        self.nama = QtWidgets.QLineEdit(formPemesanan)
        self.nama.setGeometry(QtCore.QRect(180, 270, 181, 25))
        self.nama.setObjectName("nama")
        self.nohp = QtWidgets.QLineEdit(formPemesanan)
        self.nohp.setGeometry(QtCore.QRect(180, 300, 181, 25))
        self.nohp.setObjectName("nohp")
        self.alamat = QtWidgets.QLineEdit(formPemesanan)
        self.alamat.setGeometry(QtCore.QRect(180, 330, 181, 25))
        self.alamat.setObjectName("alamat")
        self.yes_button = QtWidgets.QPushButton(formPemesanan)
        self.yes_button.setGeometry(QtCore.QRect(40, 450, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.yes_button.setFont(font)
        self.yes_button.setObjectName("yes_button")
        self.textEdit = QtWidgets.QTextEdit(formPemesanan)
        self.textEdit.setGeometry(QtCore.QRect(50, 370, 321, 71))
        self.textEdit.setStyleSheet("background : transparent;\n"
"background-color : transparent;\n"
"border : none;\n"
"text")
        self.textEdit.setObjectName("textEdit")
        self.back_button = QtWidgets.QPushButton(formPemesanan)
        self.back_button.setGeometry(QtCore.QRect(290, 450, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back_button.setFont(font)
        self.back_button.setObjectName("back_button")
        self.username_text = QtWidgets.QLabel(formPemesanan)
        self.username_text.setGeometry(QtCore.QRect(40, 210, 77, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")
        self.username = QtWidgets.QLineEdit(formPemesanan)
        self.username.setGeometry(QtCore.QRect(180, 210, 181, 25))
        self.username.setObjectName("username")
        self.username.setReadOnly(True)
        self.email = QtWidgets.QLineEdit(formPemesanan)
        self.email.setGeometry(QtCore.QRect(180, 240, 181, 25))
        self.email.setObjectName("email")
        self.email_text = QtWidgets.QLabel(formPemesanan)
        self.email_text.setGeometry(QtCore.QRect(40, 240, 47, 18))
        self.email.setReadOnly(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_text.setFont(font)
        self.email_text.setObjectName("email_text")
        self.retranslateUi(formPemesanan)
        QtCore.QMetaObject.connectSlotsByName(formPemesanan)

    def retranslateUi(self, formPemesanan):
        _translate = QtCore.QCoreApplication.translate
        formPemesanan.setWindowTitle(_translate("formPemesanan", "Ten Rentals - Konfirmasi"))
        self.judul_text.setText(_translate("formPemesanan", "STRUK PEMESANAN"))
        self.jenis_mobil_text.setText(_translate("formPemesanan", "Jenis Mobil :"))
        self.nama_text.setText(_translate("formPemesanan", "Nama :"))
        self.lama_text.setText(_translate("formPemesanan", "Lama Peminjaman :"))
        self.biaya_text.setText(_translate("formPemesanan", "Biaya :"))
        self.rental_text.setText(_translate("formPemesanan", "Rental"))
        self.pelanggan_text.setText(_translate("formPemesanan", "Pelanggan"))
        self.nohp_text.setText(_translate("formPemesanan", "No. HP :"))
        self.alamat_text.setText(_translate("formPemesanan", "Alamat :"))
        self.yes_button.setText(_translate("formPemesanan", "YA"))
        self.textEdit.setHtml(_translate("formPemesanan", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:142.857%; background-color:#ffffff;\"><span style=\" font-family:\'Menlo\',\'Monaco\',\'Consolas\',\'Courier New\',\'monospace\'; font-size:12pt; color:#000000; background-color:#ffffff;\">HARAP TUNJUKKAN STRUK DI KASIR UNTUK MELAKUKAN PEMBAYARAN!!!</span></p></body></html>"))
        self.back_button.setText(_translate("formPemesanan", "KEMBALI"))
        self.username_text.setText(_translate("formPemesanan", "Username :"))
        self.email_text.setText(_translate("formPemesanan", "E-Mail :"))