from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FormRental(object):
    def setupUi(self, FormRental):
        FormRental.setObjectName("FormRental")
        FormRental.resize(700, 600)
        FormRental.setMinimumSize(QtCore.QSize(700, 600))
        FormRental.setMaximumSize(QtCore.QSize(700, 600))
        FormRental.setWindowIcon(QtGui.QIcon('./Gambar/logo.jpg'))
        font = QtGui.QFont()
        font.setPointSize(8)
        FormRental.setFont(font)
        self.listKendaraan = QtWidgets.QComboBox(FormRental)
        self.listKendaraan.setGeometry(QtCore.QRect(130, 20, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.listKendaraan.setFont(font)
        self.listKendaraan.setMouseTracking(False)
        self.listKendaraan.setAutoFillBackground(False)
        self.listKendaraan.setEditable(False)
        self.listKendaraan.setObjectName("listKendaraan")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.listKendaraan.addItem("")
        self.kendaraan_text = QtWidgets.QLabel(FormRental)
        self.kendaraan_text.setGeometry(QtCore.QRect(20, 25, 99, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kendaraan_text.setFont(font)
        self.kendaraan_text.setObjectName("kendaraan_text")
        self.gambarMobil = QtWidgets.QLabel(FormRental)
        self.gambarMobil.setGeometry(QtCore.QRect(340, 20, 341, 311))
        self.gambarMobil.setMinimumSize(QtCore.QSize(341, 311))
        self.gambarMobil.setMaximumSize(QtCore.QSize(341, 311))
        self.gambarMobil.setStyleSheet("background-size : contain, cover;\n"
                                       "background-repeat : no-repeat;\n"
                                       "background-position : center;\n"
                                       "\n"
                                       "border-style : solid;\n"
                                       "border-width : 2px 2px;")
        self.gambarMobil.setText("")
        self.gambarMobil.setObjectName("gambarMobil")
        self.keterangan = QtWidgets.QLabel(FormRental)
        self.keterangan.setGeometry(QtCore.QRect(20, 70, 99, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.keterangan.setFont(font)
        self.keterangan.setObjectName("keterangan")
        self.boxKeterangan = QtWidgets.QPlainTextEdit(FormRental)
        self.boxKeterangan.setEnabled(True)
        self.boxKeterangan.setGeometry(QtCore.QRect(20, 100, 291, 231))
        self.boxKeterangan.setReadOnly(True)
        self.boxKeterangan.setObjectName("boxKeterangan")
        self.waktu_peminjaman = QtWidgets.QLabel(FormRental)
        self.waktu_peminjaman.setGeometry(QtCore.QRect(20, 350, 148, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.waktu_peminjaman.setFont(font)
        self.waktu_peminjaman.setObjectName("waktu_peminjaman")
        self.label_lama = QtWidgets.QLabel(FormRental)
        self.label_lama.setGeometry(QtCore.QRect(160, 384, 106, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_lama.setFont(font)
        self.label_lama.setObjectName("label_lama")
        self.biaya = QtWidgets.QLabel(FormRental)
        self.biaya.setGeometry(QtCore.QRect(20, 430, 45, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.biaya.setFont(font)
        self.biaya.setObjectName("biaya")
        self.biayaRental = QtWidgets.QLineEdit(FormRental)
        self.biayaRental.setGeometry(QtCore.QRect(20, 460, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.biayaRental.setFont(font)
        self.biayaRental.setReadOnly(True)
        self.biayaRental.setObjectName("biayaRental")
        self.btn_pesan = QtWidgets.QPushButton(FormRental)
        self.btn_pesan.setGeometry(QtCore.QRect(20, 530, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_pesan.setFont(font)
        self.btn_pesan.setObjectName("btn_pesan")
        self.btn_kembali = QtWidgets.QPushButton(FormRental)
        self.btn_kembali.setGeometry(QtCore.QRect(600, 530, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_kembali.setFont(font)
        self.btn_kembali.setObjectName("btn_kembali")
        self.listWaktu = QtWidgets.QComboBox(FormRental)
        self.listWaktu.setGeometry(QtCore.QRect(70, 380, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWaktu.setFont(font)
        self.listWaktu.setObjectName("listWaktu")
        self.listWaktu.addItem("")
        self.listWaktu.addItem("")
        self.listWaktu.addItem("")
        self.listWaktu.addItem("")
        self.label_waktu = QtWidgets.QLabel(FormRental)
        self.label_waktu.setGeometry(QtCore.QRect(20, 384, 36, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_waktu.setFont(font)
        self.label_waktu.setObjectName("label_waktu")
        self.listLamaHari = QtWidgets.QComboBox(FormRental)
        self.listLamaHari.setGeometry(QtCore.QRect(280, 380, 77, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listLamaHari.setFont(font)
        self.listLamaHari.setObjectName("listLamaHari")
        self.listLamaHari.addItem("")
        self.listLamaHari.addItem("")
        self.listLamaHari.addItem("")
        self.listLamaHari.addItem("")
        self.listLamaHari.addItem("")
        self.listLamaHari.addItem("")
        self.listLamaJam = QtWidgets.QComboBox(FormRental)
        self.listLamaJam.setGeometry(QtCore.QRect(280, 380, 77, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listLamaJam.setFont(font)
        self.listLamaJam.setObjectName("listLamaJam")
        self.listLamaJam.addItem("")
        self.listLamaJam.addItem("")
        self.listLamaJam.addItem("")
        self.listLamaJam.addItem("")
        self.listLamaJam.addItem("")
        self.listLamaBulan = QtWidgets.QComboBox(FormRental)
        self.listLamaBulan.setGeometry(QtCore.QRect(280, 380, 77, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listLamaBulan.setFont(font)
        self.listLamaBulan.setObjectName("listLamaBulan")
        self.listLamaBulan.addItem("")
        self.listLamaBulan.addItem("")
        self.listLamaMinggu = QtWidgets.QComboBox(FormRental)
        self.listLamaMinggu.setGeometry(QtCore.QRect(280, 380, 77, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listLamaMinggu.setFont(font)
        self.listLamaMinggu.setObjectName("listLamaMinggu")
        self.listLamaMinggu.addItem("")
        self.listLamaMinggu.addItem("")
        self.listLamaMinggu.addItem("")
        self.listLamaMinggu.raise_()
        self.listLamaBulan.raise_()
        self.listKendaraan.raise_()
        self.kendaraan_text.raise_()
        self.gambarMobil.raise_()
        self.keterangan.raise_()
        self.boxKeterangan.raise_()
        self.waktu_peminjaman.raise_()
        self.label_lama.raise_()
        self.biaya.raise_()
        self.biayaRental.raise_()
        self.btn_pesan.raise_()
        self.btn_kembali.raise_()
        self.listWaktu.raise_()
        self.label_waktu.raise_()
        self.listLamaHari.raise_()
        self.listLamaJam.raise_()
        self.listWaktu.currentIndexChanged.connect(self.current_lama_peminjaman)
        self.retranslateUi(FormRental)
        QtCore.QMetaObject.connectSlotsByName(FormRental)

    def retranslateUi(self, FormRental):
        _translate = QtCore.QCoreApplication.translate
        FormRental.setWindowTitle(_translate("FormRental", "Ten Rentals - Mobil"))
        self.listKendaraan.setItemText(0, _translate("FormRental", "Pilihan Anda..."))
        self.listKendaraan.setItemText(1, _translate("FormRental", "Mitsubishi Pajero Sport"))
        self.listKendaraan.setItemText(2, _translate("FormRental", "Honda CRV"))
        self.listKendaraan.setItemText(3, _translate("FormRental", "Suzuki Ertiga"))
        self.listKendaraan.setItemText(4, _translate("FormRental", "Toyota Fortuner"))
        self.listKendaraan.setItemText(5, _translate("FormRental", "Daihatsu Ayla"))
        self.listKendaraan.setItemText(6, _translate("FormRental", "Wuling Confero"))
        self.kendaraan_text.setText(_translate("FormRental", "Kendaraan :"))
        self.keterangan.setText(_translate("FormRental", "Keterangan : "))
        self.waktu_peminjaman.setText(_translate("FormRental", "Waktu Peminjaman :"))
        self.label_lama.setText(_translate("FormRental", "Lama peminjaman"))
        self.biaya.setText(_translate("FormRental", "Biaya :"))
        self.btn_pesan.setText(_translate("FormRental", "Pesan"))
        self.btn_kembali.setText(_translate("FormRental", "Kembali"))
        self.listWaktu.setItemText(0, _translate("FormRental", "Per-jam"))
        self.listWaktu.setItemText(1, _translate("FormRental", "Harian"))
        self.listWaktu.setItemText(2, _translate("FormRental", "Mingguan"))
        self.listWaktu.setItemText(3, _translate("FormRental", "Bulanan"))
        self.label_waktu.setText(_translate("FormRental", "Waktu"))
        self.listLamaHari.setItemText(0, _translate("FormRental", "1 Hari"))
        self.listLamaHari.setItemText(1, _translate("FormRental", "2 Hari"))
        self.listLamaHari.setItemText(2, _translate("FormRental", "3 Hari"))
        self.listLamaHari.setItemText(3, _translate("FormRental", "4 Hari"))
        self.listLamaHari.setItemText(4, _translate("FormRental", "5 Hari"))
        self.listLamaHari.setItemText(5, _translate("FormRental", "6 Hari"))
        self.listLamaJam.setItemText(0, _translate("FormRental", "3 Jam"))
        self.listLamaJam.setItemText(1, _translate("FormRental", "6 Jam"))
        self.listLamaJam.setItemText(2, _translate("FormRental", "9 Jam"))
        self.listLamaJam.setItemText(3, _translate("FormRental", "12 Jam"))
        self.listLamaJam.setItemText(4, _translate("FormRental", "18 Jam"))
        self.listLamaMinggu.setItemText(0, _translate("FormRental", "1 Minggu"))
        self.listLamaMinggu.setItemText(1, _translate("FormRental", "2 Minggu"))
        self.listLamaMinggu.setItemText(2, _translate("FormRental", "3 Minggu"))
        self.listLamaBulan.setItemText(0, _translate("FormRental", "1 Bulan"))
        self.listLamaBulan.setItemText(1, _translate("FormRental", "2 Bulan"))

    #fungsi untuk menampilkan QComboBox berdasarkan list waktu yang dipilih
    def current_lama_peminjaman(self):
        waktu = self.listWaktu.currentText()
        if waktu == 'Per-jam':
            self.listLamaJam.show()
            self.listLamaHari.hide()
            self.listLamaBulan.hide()
            self.listLamaMinggu.hide()
        elif waktu == 'Harian':
            self.listLamaJam.hide()
            self.listLamaHari.show()
            self.listLamaBulan.hide()
            self.listLamaMinggu.hide()
        elif waktu == 'Mingguan':
            self.listLamaJam.hide()
            self.listLamaHari.hide()
            self.listLamaMinggu.show()
            self.listLamaBulan.hide()
        elif waktu == 'Bulanan':
            self.listLamaJam.hide()
            self.listLamaHari.hide()
            self.listLamaMinggu.hide()
            self.listLamaBulan.show()